version: '3'

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - twitch-dash-web
  twitch-dash-web:
    build: ./app
    expose:
      - 80
    ports:
      - 80:80
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    links:
      - twitch-dash-api
    depends_on:
      - twitch-dash-api
  twitch-dash-api:
    build: ./server
    expose:
      - 4000
    ports:
      - 4000:4000
